#!/usr/bin/env ruby

require_relative 'bootstrap_ar'

database = ENV['FP_ENV'] || 'development'
connect_to database

command = nil
command = ARGV.shift.downcase unless ARGV == []
command += ' ' + ARGV.shift.downcase if command == 'add' || command == 'delete'
name = ARGV[0..-1].join(' ').downcase unless ARGV.nil?

recipe_params = { command: command, recipe: { name: name } }
ingredient_params = { command: command, ingredient: { name: name } }
recipe_controller = RecipeController.new(recipe_params)
ingredient_controller = IngredientController.new(ingredient_params)
question_set = QuestionSet.new

case command
when nil
  MenuView.render_menu
when 'style'
  StyleView.render_definition
when 'techniques'
  TechniquesView.render_list
when 'add ingredient'
  ingredient_controller.create
when 'ingredients'
  ingredient_controller.list_ingredients
when 'delete ingredient'
  ingredient_controller.delete
when 'build'
  question_set.menu
when 'add recipe'
  recipe_controller.create
when 'view'
  recipe_controller.view
when 'list'
  recipe_controller.list_recipes
when 'delete recipe'
  recipe_controller.delete
else
  puts "\nThat is not a valid command. Type sb to view a list of commands."
end
