#!/usr/bin/env ruby

require_relative 'bootstrap_ar'

database = ENV['FP_ENV'] || 'development'
connect_to database

command = nil
command = ARGV[0].downcase unless ARGV[0].nil?
name = ARGV[1]
index = 2
until ARGV[index].nil? do
  name += ' ' + ARGV[index]
  index += 1
end

params = { command: command, recipe: { name: name } }
recipe_controller = RecipeController.new(params)
ingredient_controller = IngredientController.new
question_set = QuestionSet.new

case command
when nil
  Menu.render_menu
when 'style'
  Style.render_definition
when 'techniques'
  Techniques.render_list
when 'ingredients'
  ingredient_controller.list_ingredients
when 'build'
  question_set.menu
when 'add'
  recipe_controller.create
when 'view'
  recipe_controller.view
when 'list'
  recipe_controller.list_recipes
when 'delete'
  recipe_controller.delete
end
