class SeedIngredients < ActiveRecord::Migration

  def change
    Ingredient.create( name: 'Pilsner', description: 'Pale base malt, prominent in continental examples.', type_code: 1 )
    Ingredient.create( name: '2-row Pale Malt', description: 'Pale base malt, commonly used in American examples.', type_code: 1 )
    Ingredient.create( name: 'Munich', description: 'Base malt, adds richness. Use to supplement wheat, pilsner, or pale malt.', type_code: 1 )
    Ingredient.create( name: 'White Wheat Malt', description: 'Base malt, added to modify malt character. Doughy, mild.', type_code: 1 )
    Ingredient.create( name: 'Caramunich 60', description: 'Caramel malt, adds mild caramel/toffee flavors and sweetness.', type_code: 1 )
    Ingredient.create( name: 'Honey Malt', description: 'Specialty malt. Adds distinctive honey-like sweetness.', type_code: 1 )
    Ingredient.create( name: 'Chocolate Malt', description: 'Kilned specialty malt. Adds nutty, chocolate flavor and color.', type_code: 1 )
    Ingredient.create( name: 'Carafa 2 Special', description: 'Kilned specialty malt. Adds color, mild roasty flavors w/o harshness.', type_code: 1 )
    Ingredient.create( name: 'Amarillo', description: 'New-world hop, floral, tangerine citrus character.', type_code: 2 )
    Ingredient.create( name: 'Hallertau', description: 'Old-world, floral, spicy, refined.', type_code: 2 )
    Ingredient.create( name: 'Saaz', description: 'Old-world, spicy, earthy.', type_code: 2 )
    Ingredient.create( name: 'Simcoe', description: 'New-world, pungent, pine, grapefruit, pineapple.', type_code: 2 )
    Ingredient.create( name: 'Sorachi', description: 'New-world, clean, string lemon character, bright.', type_code: 2 )
    Ingredient.create( name: 'Styrian Goldings', description: 'Old-world, spicy, mildly floral, fruity.', type_code: 2 )
    Ingredient.create( name: 'Dupont Strain', description: 'Ferment: ~85F, can be slow to finish. Spicy/peppery, mild fruit.', type_code: 3, yeast_code_wyeast: 3724, yeast_code_wl: 565 )
    Ingredient.create( name: 'French Saison', description: 'Ferment: 65-72F. Aromatic fruit/citrus, peppery, clean.', type_code: 3, yeast_code_wyeast: 3711, yeast_code_wl: 656 )
    Ingredient.create( name: 'American Farmhouse', description: 'Ferment: 65-72F. Saison/Brett blend. Mild pepper, barnyard.', type_code: 3, yeast_code_wl: 670 )
    Ingredient.create( name: 'Brett. Brux. Trois', description: 'Ferment: 65-72F. Mild, tart, delicate mango, pineapple.' , type_code: 3, yeast_code_wl: 644 )
    Ingredient.create( name: 'Brett. Brux.', description: 'Ferment: 65-72F. Moderate intensity, horseblanket, bright lemon.', type_code: 3, yeast_code_wyeast: 5112, yeast_code_wl: 650 )
    Ingredient.create( name: 'Brett. Clausenii', description: 'Ferment: 65-72F. Prominent pineapple/tropical fruit aromatics.', type_code: 3, yeast_code_wl: 645 )
    Ingredient.create( name: 'Brett. Lambicus', description: 'Ferment: 65-72F. Intense, barnyard, horseblanket, dank, musty.', type_code: 3, yeast_code_wyeast: 5526, yeast_code_wl: 653 )
    Ingredient.create( name: 'Cardamom', description: 'Adds a citrusy, ginger-like flavor with elements of cinnamon or nutmeg.', type_code: 4 )
    Ingredient.create( name: 'Citrus Zest', description: 'Can use an array of varieties - lemon, lime, orange, etc.', type_code: 4 )
    Ingredient.create( name: 'White Peppercorns', description: 'Peppery, mild wine-like flavor.', type_code: 4 )
    Ingredient.create( name: 'Thai Basil', description: 'Similar to sweet basil, but with notes of licorice.', type_code: 4 )
    Ingredient.create( name: 'Ginger', description: 'Clean, warm, woody sweetness, bright.', type_code: 4 )
    Ingredient.create( name: 'Peaches', description: 'Add to secondary fermentation.', type_code: 5 )
    Ingredient.create( name: 'Blackberries', description: 'Add to secondary fermentation.', type_code: 5 )
    Ingredient.create( name: 'Mango', description: 'Add to secondary fermentation. Tropical-fruit character, mildly tart.', type_code: 5 )
    Ingredient.create( name: 'Currants', description: 'Tart, raisin-like flavor. Add to secondary fermentation.', type_code: 5 )
    Ingredient.create( name: 'Hibiscus', description: 'Deep red in color, fruity flavor, notes of lemon and ripe berries.', type_code: 6 )
    Ingredient.create( name: 'Lavender', description: 'Floral, spicy, notes of lemon and mint.', type_code: 6 )
    Ingredient.create( name: 'Rose Hips', description: 'Floral, citrusy, sour.', type_code: 6 )
    Ingredient.create( name: 'Corn Sugar', description: 'Adjunct. Adds no flavor; add to raise gravity without boosting body.', type_code: 7 )
    Ingredient.create( name: 'Turbinado Sugar', description: 'Adjunct. Adds subtle molasses character.', type_code: 7 )
    Ingredient.create( name: 'Rice', description: 'Adjunct. Adds crispness, lightens body. Cook before adding to mash.', type_code: 7 )
  end
end